# Generated by Django 2.2.5 on 2019-10-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.CharField(max_length=200, verbose_name='Article name')),
                ('articleText', models.TextField(verbose_name='Main text')),
                ('pupDate', models.DateField(verbose_name='Publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=50, verbose_name='Authors name')),
                ('commentText', models.CharField(max_length=200, verbose_name='Text field')),
                ('pubDate', models.DateField(verbose_name='Publication date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
